server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    virtual-host: /askingshop
    username: /askingshop
    password: askingshop
    host: 192.168.136.135

asking:
  sms:
    accessKeyId: LTAIAmUoi6ZhVUJn
    accessKeySecret: 5YuCHRrFOV0HtubpEY1G0cEA0zjP5e
    SignName: AskingShop商城
    verify-code-template: SMS_170330126
