spring:
  application:
    name: item-service-interface
  datasource:
    url: jdbc:mysql://localhost:3306/askingshop?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  main:
    allow-bean-definition-overriding: true
